#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing dependency: $1" >&2
    exit 1
  fi
}

need wtf-upload

OUT_DIR="${1:-$ROOT/screenshots}"
mkdir -p "$OUT_DIR"

echo "[1/4] Regenerate screenshots"
"$ROOT/scripts/make_screenshots.sh" "$OUT_DIR"

declare -a keys=(
  "mixer.png"
  "visualizer.png"
  "patchbay.png"
  "graph.png"
  "settings.png"
  "eq.png"
  "engine.png"
  "tray-menu.png"
)
declare -a titles=(
  "Mixer"
  "Visualizer"
  "Patchbay"
  "Graph"
  "Settings"
  "Parametric EQ"
  "Engine"
  "Tray menu"
)
declare -a alts=(
  "Mixer tab screenshot"
  "Visualizer tab screenshot"
  "Patchbay tab screenshot"
  "Graph tab screenshot"
  "Settings dialog screenshot"
  "Parametric EQ dialog screenshot"
  "Engine dialog screenshot"
  "Tray menu screenshot"
)

echo "[2/4] Upload screenshots"
upload_paths=()
upload_keys=()
for i in "${!keys[@]}"; do
  f="${OUT_DIR}/${keys[$i]}"
  if [[ -f "$f" ]]; then
    upload_paths+=("$f")
    upload_keys+=("${keys[$i]}")
  else
    echo "warn: missing screenshot: $f" >&2
  fi
done

if [[ ${#upload_paths[@]} -eq 0 ]]; then
  echo "No screenshots found in $OUT_DIR" >&2
  exit 1
fi

upload_output="$(wtf-upload "${upload_paths[@]}")" || {
  echo "wtf-upload failed. Configure AWS credentials first (e.g. run: aws configure)." >&2
  exit 1
}
mapfile -t uploaded_urls <<<"$upload_output"
if [[ ${#uploaded_urls[@]} -ne ${#upload_paths[@]} ]]; then
  echo "Upload output mismatch: expected ${#upload_paths[@]} urls, got ${#uploaded_urls[@]}" >&2
  exit 1
fi

declare -A url_by_key=()
for i in "${!uploaded_urls[@]}"; do
  url_by_key["${upload_keys[$i]}"]="${uploaded_urls[$i]}"
done

INDEX_PATH="$ROOT/screenshots/index.html"
tmp="$(mktemp)"

echo "[3/4] Write screenshots/index.html"
cat >"$tmp" <<'EOF'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Headroom — Screenshots</title>
    <style>
      :root {
        color-scheme: dark;
        --bg: #0b0f19;
        --panel: #0f172a;
        --text: #e2e8f0;
        --muted: #94a3b8;
        --border: #24304a;
      }
      html,
      body {
        margin: 0;
        padding: 0;
        background: var(--bg);
        color: var(--text);
        font: 14px/1.4 system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, sans-serif;
      }
      .wrap {
        max-width: 1100px;
        margin: 24px auto;
        padding: 0 16px 48px;
      }
      header {
        margin-bottom: 18px;
      }
      h1 {
        margin: 0 0 6px;
        font-size: 22px;
      }
      p {
        margin: 0;
        color: var(--muted);
      }
      section {
        margin-top: 16px;
        background: linear-gradient(180deg, rgba(255, 255, 255, 0.04), rgba(255, 255, 255, 0.015));
        border: 1px solid var(--border);
        border-radius: 14px;
        overflow: hidden;
      }
      section h2 {
        margin: 0;
        padding: 12px 14px;
        font-size: 15px;
        font-weight: 650;
        border-bottom: 1px solid var(--border);
        background: rgba(15, 23, 42, 0.75);
      }
      section .content {
        padding: 12px;
      }
      img {
        width: 100%;
        height: auto;
        border-radius: 10px;
        border: 1px solid rgba(148, 163, 184, 0.18);
        background: #0b0f19;
      }
      .meta {
        display: flex;
        gap: 12px;
        flex-wrap: wrap;
        margin-top: 10px;
        color: var(--muted);
        font-size: 12px;
      }
      a {
        color: #7dd3fc;
        text-decoration: none;
      }
      a:hover {
        text-decoration: underline;
      }
      code {
        background: rgba(148, 163, 184, 0.1);
        padding: 1px 6px;
        border-radius: 6px;
      }
    </style>
  </head>
  <body>
    <div class="wrap">
      <header>
        <h1>Headroom — Screenshots</h1>
        <p>Auto-generated by <code>./scripts/publish_screenshots.sh</code>.</p>
        <div class="meta">
          <span>Generate: <code>./scripts/make_screenshots.sh</code></span>
          <span>Upload: <code>wtf-upload screenshots/*.png</code></span>
        </div>
      </header>
EOF

for i in "${!keys[@]}"; do
  key="${keys[$i]}"
  url="${url_by_key[$key]:-}"
  [[ -z "$url" ]] && continue

  cat >>"$tmp" <<EOF

      <section>
        <h2>${titles[$i]}</h2>
        <div class="content">
          <a href="${url}" target="_blank" rel="noreferrer">
            <img alt="${alts[$i]}" src="${url}" />
          </a>
        </div>
      </section>
EOF
done

cat >>"$tmp" <<'EOF'
    </div>
  </body>
</html>
EOF

mv "$tmp" "$INDEX_PATH"

echo "[4/4] Upload screenshots/index.html"
index_url="$(wtf-upload --content-type text/html --cache-control "no-cache" "$INDEX_PATH")"

echo
echo "Gallery:"
echo "  $index_url"
echo
echo "Images:"
for k in "${keys[@]}"; do
  if [[ -n "${url_by_key[$k]:-}" ]]; then
    echo "  $k  ${url_by_key[$k]}"
  fi
done
